-   id: recipe-spell-checker
    name: Recipe spell checker
    description: Ensures that there aren't any spelling mistakes in the recipes
    entry: recipe-spell-checker
    language: python
    types: [html]
